spring:
  profiles:
    active: development

server:
  port: 9002

application:
  name: Service Credit Management 
  description: API created to manage loans 

integrators:
  data:
    port: 3002
  providers:
    port: 3000

---

spring:
  config:
    activate:
      on-profile: development
integrators:
  data:
    ip: localhost
  providers:
    ip: localhost

---

spring:
  config:
    activate:
      on-profile: test
integrators:
  data:
    ip: 10.1.0.19
  providers:
    ip: 10.2.0.193

---

spring:
  config:
    activate:
      on-profile: production
integrators:
  data:
    ip: 10.1.0.115
  providers:
    ip: 10.2.0.225